apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-deployment
  name: frontend-service
spec:
  ports:
  - port: 32001
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-deployment
  type: NodePort
status:
  loadBalancer: {}
