resources:
- frontend/deployment.yml
- frontend/service.yml
- backend/deployment.yml
- backend/service.yml
- ingress.yml
images:
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/backend
  newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/backend
  newTag: 59e40892b9bf58443da2702e8043348f76b177a5
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/frontend
  newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/frontend
  newTag: 59e40892b9bf58443da2702e8043348f76b177a5
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
