resources:
- frontend/deployment.yml
- frontend/service.yml
- backend/deployment.yml
- backend/service.yml
- ingress.yml
images:
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/backend
  newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/backend
  newTag: 37fb6b26b54d58bb25cfd868983fba4f20cff57b
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/frontend
  newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/frontend
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
