resources:
- frontend/deployment.yml
- frontend/service.yml
- backend/deployment.yml
- backend/service.yml
- ingress.yml
images:
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/backend
  newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/backend
  newTag: 94a3fe572c49ed3759053a3ba75ea26109e59fea
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/frontend
  newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/youtube-live/production/frontend
  newTag: 94a3fe572c49ed3759053a3ba75ea26109e59fea
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
