apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-deployment
  name: backend-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /backend/health
spec:
  ports:
  - port: 32000
    protocol: TCP
    targetPort: 80
  selector:
    app: backend-deployment
  type: NodePort
status:
  loadBalancer: {}
